kind = "web"
previewPath = "/"
title = "Bizny"
version = "1.0.0"
id = "artifacts/bizny"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 25817

[services.development]
run = "pnpm --filter @workspace/bizny run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/bizny", "run", "build" ]
publicDir = "artifacts/bizny/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "25817"
BASE_PATH = "/"
