import { Router, type IRouter } from "express";
import dealsRouter from "./deals";
import uploadRouter from "./upload";
import innovationsRouter from "./innovations";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import opportunitiesRouter from "./opportunities";
import marketplaceRouter from "./marketplace";
import templatesRouter from "./templates";
import venturesRouter from "./ventures";
import feedRouter from "./feed";
import copilotRouter from "./copilot";
import updatesRouter from "./updates";
import notificationsRouter from "./notifications";
import dashboardRouter from "./dashboard";
import openaiRouter from "./openai";
import followsRouter from "./follows";
import fieldAgentRouter from "./field_agent";
import industryTargetsRouter from "./industry_targets";
import executionInstancesRouter from "./execution-instances";
import coachRouter from "./coach";
import dealTypesRouter from "./deal-types";
import knowledgeArticlesRouter from "./knowledge-articles";
import researchRouter from "./research";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(opportunitiesRouter);
router.use(marketplaceRouter);
router.use(templatesRouter);
router.use(venturesRouter);
router.use(feedRouter);
router.use(copilotRouter);
router.use(updatesRouter);
router.use(notificationsRouter);
router.use(dashboardRouter);
router.use(openaiRouter);
router.use(followsRouter);
router.use(fieldAgentRouter);
router.use(industryTargetsRouter);
router.use(dealsRouter);
router.use(uploadRouter);
router.use(innovationsRouter);
router.use(executionInstancesRouter);
router.use(coachRouter);
router.use(dealTypesRouter);
router.use(knowledgeArticlesRouter);
router.use("/research", researchRouter);

export default router;
